
services:
  whatsapp-server-api:
    build: .
    container_name: whatsapp-server-api
    restart: unless-stopped
    #network_mode: host
    ports:
      - "127.0.0.1:3001:3001" # Accessible only from the host machine
    env_file: .env
    #volumes:
      # Maps your existing local auth folder into the container
      #- ./auth:/app/auth_info_baileys

